Repository prgrms-be-devcourse/BEDV1_LocalInfo, pull requests merged in 2021-11, with the labels that each got.

#29 test: CommentServiceTest 통합테스트 대신 단위테스트로 변경
  src/test/java/com/kdt/localinfo/comment/service/CommentServiceTest.java
Labels: :recycle: refactor, LocalInfo

#37 feat: jacoco 관련 설정 파일 추가
  build.gradle
  lombok.config
Labels: ✨ feat

#47 refactor: UserController 테스트 버그 해결
  build.gradle
  src/test/java/com/kdt/localinfo/user/controller/UserControllerTest.java
Labels: 🐛 bug, :recycle: refactor

#53 v1.1 배포
  build.gradle
  src/main/java/com/kdt/localinfo/comment/controller/CommentController.java
  src/main/java/com/kdt/localinfo/comment/entity/Comment.java
  src/main/java/com/kdt/localinfo/comment/repository/CommentRepository.java
  src/main/java/com/kdt/localinfo/comment/service/CommentService.java
  src/main/java/com/kdt/localinfo/common/JasyptConfig.java
  src/main/java/com/kdt/localinfo/photo/Photo.java
  src/main/java/com/kdt/localinfo/post/entity/Post.java
  src/main/java/com/kdt/localinfo/user/controller/UserController.java
  src/main/java/com/kdt/localinfo/user/entity/User.java
  src/main/java/com/kdt/localinfo/user/service/UserService.java
  src/test/java/com/kdt/localinfo/LocalInfoApplicationTests.java
  src/test/java/com/kdt/localinfo/comment/controller/CommentControllerTest.java
  src/test/java/com/kdt/localinfo/comment/service/CommentServiceTest.java
  src/test/java/com/kdt/localinfo/common/TestEntityFactory.java
  src/test/java/com/kdt/localinfo/user/controller/UserControllerTest.java
  src/test/java/com/kdt/localinfo/user/entity/UserTest.java
  src/test/java/com/kdt/localinfo/user/service/UserServiceTest.java
  src/test/resources/application-test.yml
Labels: :rocket: deploy

#57 feat: 유저 수정 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/kdt/localinfo/LocalInfoApplication.java
  src/main/java/com/kdt/localinfo/comment/controller/CommentController.java
  src/main/java/com/kdt/localinfo/common/BaseEntity.java
  src/main/java/com/kdt/localinfo/common/ValidationException.java
  src/main/java/com/kdt/localinfo/error/ErrorResources.java
  src/main/java/com/kdt/localinfo/error/ErrorsSerializer.java
  src/main/java/com/kdt/localinfo/error/GeneralExceptionHandler.java
  src/main/java/com/kdt/localinfo/error/InvalidInputException.java
  src/main/java/com/kdt/localinfo/user/controller/UserController.java
  src/main/java/com/kdt/localinfo/user/dto/UserResponse.java
  src/main/java/com/kdt/localinfo/user/entity/Role.java
  src/main/java/com/kdt/localinfo/user/entity/User.java
  src/main/java/com/kdt/localinfo/user/service/UserService.java
  src/test/java/com/kdt/localinfo/user/controller/UserControllerTest.java
  src/test/java/com/kdt/localinfo/user/service/UserServiceTest.java
Labels: ✨ feat

#61 feat: 게시물 수정, 삭제 기능 추가
  build.gradle
  post-photo/test.png
  src/main/java/com/kdt/localinfo/comment/controller/CommentController.java
  src/main/java/com/kdt/localinfo/comment/repository/CommentRepository.java
  src/main/java/com/kdt/localinfo/common/ApiResponse.java
  src/main/java/com/kdt/localinfo/post/controller/PostController.java
  src/main/java/com/kdt/localinfo/post/converter/PostConverter.java
  src/main/java/com/kdt/localinfo/post/dto/PostCreateRequest.java
  src/main/java/com/kdt/localinfo/post/dto/PostDto.java
  src/main/java/com/kdt/localinfo/post/dto/PostResponse.java
  src/main/java/com/kdt/localinfo/post/dto/PostUpdateRequest.java
  src/main/java/com/kdt/localinfo/post/entity/Post.java
  src/main/java/com/kdt/localinfo/post/repository/PostRepository.java
  src/main/java/com/kdt/localinfo/post/service/PostService.java
  src/main/java/com/kdt/localinfo/post/service/S3Service.java
  src/main/java/com/kdt/localinfo/user/repository/UserRepository.java
  src/main/resources/README.md
  src/main/resources/check-sub-module
  src/test/java/com/kdt/localinfo/comment/controller/CommentControllerTest.java
  src/test/java/com/kdt/localinfo/common/TestEntityFactory.java
  src/test/java/com/kdt/localinfo/post/controller/PostControllerTest.java
  src/test/java/com/kdt/localinfo/post/entity/PostTest.java
  src/test/java/com/kdt/localinfo/post/service/PostServiceTest.java
  src/test/java/com/kdt/localinfo/user/controller/UserControllerTest.java
Labels: ✨ feat
